export 'package:ondgo_flutter/view/screens/Splash/splash_screen.dart';
export 'package:ondgo_flutter/view/screens/Splash/splash_screen1.dart';
export 'package:ondgo_flutter/view/screens/login/login_screen.dart';
export 'package:ondgo_flutter/view/screens/profile/profile_screen.dart';
export 'package:ondgo_flutter/view/screens/contact/contacts.dart';
export 'package:ondgo_flutter/view/screens/feedback/feedback_screen.dart';
export 'package:ondgo_flutter/view/screens/help/help_screen.dart';
export 'package:ondgo_flutter/view/screens/language/language_screen.dart';
export 'package:ondgo_flutter/view/screens/playlist/playlist_screen.dart';
export 'package:ondgo_flutter/view/screens/purchases/purchase_screen.dart';
export 'package:ondgo_flutter/view/screens/rewards/rewards_screen.dart';
export 'package:ondgo_flutter/view/screens/events/events_screen.dart';
export 'package:ondgo_flutter/view/screens/showcase/showcase_screen.dart';
export 'package:ondgo_flutter/view/screens/reels/reels_screen.dart';
export 'package:ondgo_flutter/view/screens/homescreen/home.dart';
export 'package:ondgo_flutter/view/screens/reels/reels_full_screen.dart';
// export 'package:ondgo_flutter/view/screens/search/search_library_screen.dart';
